on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, "feature/*", "hotfix/*", "release/*" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '7.0.x', '8.0.x' ]
    name: Tests .NET${{ matrix.dotnet }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Add NuGet source
        run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      - name: Build Source Generator
        run: dotnet build -c Release ./src/ApiRoutes.Generator
      - name: Run Tests
        run: dotnet test build.proj
        env: 
          OVERRIDEFRAMEWORK: true
          RUN_TESTS: true